services:
  - type: web
    name: neekan
    runtime: java
    rootDir: backend/ecom
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/ecom-0.0.1-SNAPSHOT.jar
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_API_KEY
        sync: false


